USB_VID = 0x239A
USB_PID = 0x8026
USB_PRODUCT = "Feather M4 Express"
USB_MANUFACTURER = "Adafruit Industries LLC"

CHIP_VARIANT = SAME51J19A
CHIP_FAMILY = same51

INTERNAL_FLASH_FILESYSTEM = 1
# EXTERNAL_FLASH_DEVICES = GD25Q16C
LONGINT_IMPL = MPZ
CIRCUITPY_FULL_BUILD = 0

CIRCUITPY__EVE = 1
