#include "shared-bindings/board/__init__.h"

STATIC const mp_rom_map_elem_t board_module_globals_table[] = {
    CIRCUITPYTHON_BOARD_DICT_STANDARD_ITEMS

    { MP_ROM_QSTR(MP_QSTR_D1), MP_ROM_PTR(&pin_PA06) },
    { MP_ROM_QSTR(MP_QSTR_BATT), MP_ROM_PTR(&pin_PA06) },

    { MP_ROM_QSTR(MP_QSTR_D2), MP_ROM_PTR(&pin_PA07) },
    { MP_ROM_QSTR(MP_QSTR_ACCCS), MP_ROM_PTR(&pin_PA07) },

    { MP_ROM_QSTR(MP_QSTR_D3), MP_ROM_PTR(&pin_PA11) },
    { MP_ROM_QSTR(MP_QSTR_WIFICS), MP_ROM_PTR(&pin_PA11) },

    { MP_ROM_QSTR(MP_QSTR_D4), MP_ROM_PTR(&pin_PA13) },
    { MP_ROM_QSTR(MP_QSTR_A0), MP_ROM_PTR(&pin_PA13) },

    { MP_ROM_QSTR(MP_QSTR_D5), MP_ROM_PTR(&pin_PA14) },
    { MP_ROM_QSTR(MP_QSTR_DISRES), MP_ROM_PTR(&pin_PA14) },

    { MP_ROM_QSTR(MP_QSTR_D6), MP_ROM_PTR(&pin_PA15) },
    { MP_ROM_QSTR(MP_QSTR_THERM), MP_ROM_PTR(&pin_PA15) },



    { MP_ROM_QSTR(MP_QSTR_D7), MP_ROM_PTR(&pin_PA16) },
    { MP_ROM_QSTR(MP_QSTR_DB0), MP_ROM_PTR(&pin_PA16) },

    { MP_ROM_QSTR(MP_QSTR_D8), MP_ROM_PTR(&pin_PA17) },
    { MP_ROM_QSTR(MP_QSTR_DB1), MP_ROM_PTR(&pin_PA17) },

    { MP_ROM_QSTR(MP_QSTR_D9), MP_ROM_PTR(&pin_PA18) },
    { MP_ROM_QSTR(MP_QSTR_DB2), MP_ROM_PTR(&pin_PA18) },

    { MP_ROM_QSTR(MP_QSTR_D10), MP_ROM_PTR(&pin_PA19) },
    { MP_ROM_QSTR(MP_QSTR_DB3), MP_ROM_PTR(&pin_PA19) },

    { MP_ROM_QSTR(MP_QSTR_D11), MP_ROM_PTR(&pin_PA20) },
    { MP_ROM_QSTR(MP_QSTR_DB4), MP_ROM_PTR(&pin_PA20) },

    { MP_ROM_QSTR(MP_QSTR_D12), MP_ROM_PTR(&pin_PA21) },
    { MP_ROM_QSTR(MP_QSTR_DB5), MP_ROM_PTR(&pin_PA21) },

    { MP_ROM_QSTR(MP_QSTR_D13), MP_ROM_PTR(&pin_PA22) },
    { MP_ROM_QSTR(MP_QSTR_DB6), MP_ROM_PTR(&pin_PA22) },

    { MP_ROM_QSTR(MP_QSTR_D14), MP_ROM_PTR(&pin_PA23) },
    { MP_ROM_QSTR(MP_QSTR_DB7), MP_ROM_PTR(&pin_PA23) },

    { MP_ROM_QSTR(MP_QSTR_SCK), MP_ROM_PTR(&pin_PA08) },
    { MP_ROM_QSTR(MP_QSTR_D25), MP_ROM_PTR(&pin_PA08) },

    { MP_ROM_QSTR(MP_QSTR_MOSI), MP_ROM_PTR(&pin_PA09) },
    { MP_ROM_QSTR(MP_QSTR_D24), MP_ROM_PTR(&pin_PA09) },

    { MP_ROM_QSTR(MP_QSTR_MISO), MP_ROM_PTR(&pin_PA10) },
    { MP_ROM_QSTR(MP_QSTR_D23), MP_ROM_PTR(&pin_PA10) },



    { MP_ROM_QSTR(MP_QSTR_D15), MP_ROM_PTR(&pin_PB17) },
    { MP_ROM_QSTR(MP_QSTR_RX), MP_ROM_PTR(&pin_PB17) },

    { MP_ROM_QSTR(MP_QSTR_D16), MP_ROM_PTR(&pin_PB16) },
    { MP_ROM_QSTR(MP_QSTR_TX), MP_ROM_PTR(&pin_PB16) },



    { MP_ROM_QSTR(MP_QSTR_D17), MP_ROM_PTR(&pin_PA27) },
    { MP_ROM_QSTR(MP_QSTR_DISCLK), MP_ROM_PTR(&pin_PA27) },

    { MP_ROM_QSTR(MP_QSTR_D18), MP_ROM_PTR(&pin_PB04) },
    { MP_ROM_QSTR(MP_QSTR_ONOFF), MP_ROM_PTR(&pin_PB04) },

    { MP_ROM_QSTR(MP_QSTR_D19), MP_ROM_PTR(&pin_PB05) },
    { MP_ROM_QSTR(MP_QSTR_WAKEUP), MP_ROM_PTR(&pin_PB05) },

    { MP_ROM_QSTR(MP_QSTR_D20), MP_ROM_PTR(&pin_PB06) },
    { MP_ROM_QSTR(MP_QSTR_GPSCS), MP_ROM_PTR(&pin_PB06) },

    { MP_ROM_QSTR(MP_QSTR_D21), MP_ROM_PTR(&pin_PB07) },
    { MP_ROM_QSTR(MP_QSTR_BOOSTEN), MP_ROM_PTR(&pin_PB07) },

    { MP_ROM_QSTR(MP_QSTR_D22), MP_ROM_PTR(&pin_PB10) },
    { MP_ROM_QSTR(MP_QSTR_WIFIEN), MP_ROM_PTR(&pin_PB10) },

    { MP_ROM_QSTR(MP_QSTR_D26), MP_ROM_PTR(&pin_PB11) },
    { MP_ROM_QSTR(MP_QSTR_WIFIGPIO0), MP_ROM_PTR(&pin_PB11) },

    { MP_ROM_QSTR(MP_QSTR_D27), MP_ROM_PTR(&pin_PB12) },
    { MP_ROM_QSTR(MP_QSTR_EX1), MP_ROM_PTR(&pin_PB12) },

    { MP_ROM_QSTR(MP_QSTR_D28), MP_ROM_PTR(&pin_PB13) },
    { MP_ROM_QSTR(MP_QSTR_EX2), MP_ROM_PTR(&pin_PB13) },

    { MP_ROM_QSTR(MP_QSTR_D29), MP_ROM_PTR(&pin_PB14) },
    { MP_ROM_QSTR(MP_QSTR_EX3), MP_ROM_PTR(&pin_PB14) },

    { MP_ROM_QSTR(MP_QSTR_D30), MP_ROM_PTR(&pin_PB15) },
    { MP_ROM_QSTR(MP_QSTR_EX4), MP_ROM_PTR(&pin_PB15) },

    { MP_ROM_QSTR(MP_QSTR_D31), MP_ROM_PTR(&pin_PB22) },
    { MP_ROM_QSTR(MP_QSTR_CSL), MP_ROM_PTR(&pin_PB22) },

    { MP_ROM_QSTR(MP_QSTR_D32), MP_ROM_PTR(&pin_PB23) },
    { MP_ROM_QSTR(MP_QSTR_CSR), MP_ROM_PTR(&pin_PB23) },

    { MP_ROM_QSTR(MP_QSTR_D33), MP_ROM_PTR(&pin_PB30) },
    { MP_ROM_QSTR(MP_QSTR_WRITE), MP_ROM_PTR(&pin_PB30) },

    { MP_ROM_QSTR(MP_QSTR_D34), MP_ROM_PTR(&pin_PB31) },
    { MP_ROM_QSTR(MP_QSTR_READ), MP_ROM_PTR(&pin_PB31) },

    { MP_ROM_QSTR(MP_QSTR_I2C), MP_ROM_PTR(&board_i2c_obj) },
    { MP_ROM_QSTR(MP_QSTR_SPI), MP_ROM_PTR(&board_spi_obj) },
    { MP_ROM_QSTR(MP_QSTR_UART), MP_ROM_PTR(&board_uart_obj) },
};
MP_DEFINE_CONST_DICT(board_module_globals, board_module_globals_table);
