USB_VID = 0x239A
USB_PID = 0x8026
USB_PRODUCT = "Jackie Board"
USB_MANUFACTURER = "Adafruit Industries LLC"

CHIP_VARIANT = SAMD51J20A
CHIP_FAMILY = samd51

INTERNAL_FLASH_FILESYSTEM = 1
# EXTERNAL_FLASH_DEVICES = GD25Q16C
LONGINT_IMPL = MPZ

CIRCUITPY__EVE = 1
